# Generated by Django 5.1.2 on 2024-11-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
